name: "irf_spatial_params_mix_fb"

#Integrator settings
grid:
    nr: 8
    nt: 1
    dt:
        unit: "ms"
        value: 1.0
    dr:
        unit: "deg"
        value: 0.05

#Neuron settings
ganglion:
    # DOG
    A: 1
    a:
       unit: "deg"
       value: 0.62
    B: 0.85
    b:
       unit: "deg"
       value: 1.26

relay:
    width: &width
        unit: "deg"
        start: 0.1
        stop: 3.
        count: 20
        
    weight: &weight
        start: 0.
        stop: 1.5
        count: 20
        
    Krg:
        w: 1.0
        # Gaussian
        A: 1
        a:
           unit: "deg"
           value: 0.1
           
    Krc_ex:
      w_fix: 0.6
      w: *weight
      
      # Gaussian
      A: 0.5
      a_fix: 
          unit: "deg"
          value: 0.1
      a: *width

    Krc_in:
       w_fix: 1.2
       w: *weight
       
       # Gaussian
       A: -0.5
       a_fix: 
           unit: "deg"
           value: 0.9
       a: *width
