name: "irf_temporal_params"

# Integrator settings
grid:
    nr: 7
    nt: 10
    dt:
       unit: "ms"
       value: 1
    dr:
        unit: "deg"
        value: 0.1
        
# Neuron settings
ganglion:
    # DOG
    A: 1
    a:
       unit: "deg"
       value: 0.62
    B: 0.85
    b:
       unit: "deg"
       value: 1.26

    # Biphasic
    damping: 0.38
    phase:
       unit: "ms"
       value: 43
    delay:
       unit: "ms"
       value: 0.

relay:
    weight: &weight
        start: 0.
        stop: 1.5
        count: 13
        
    delay: &delay
        unit: "ms"
        start: 5.
        stop: 30.
        count: 15
        
    Krg:
        w: 1.0
        # Gaussian
        A: 1
        a:
           unit: "deg"
           value: 0.1
           
        # exp decay
        tau:
           unit: "ms"
           value: 5.
        delay:
            unit: "ms"
            value: 0.
           
    Krig:
        w: *weight
        # Gaussian
        A: -0.5
        a:
           unit: "deg"
           value: 0.3
           
        # exp decay
        tau:
           unit: "ms"
           value: 5.
        delay: *delay
            
    Krc_ex:
      w: *weight
      # Gaussian
      A: 0.5
      a: 
          unit: "deg"
          value: 0.83
          
      # exp decay
      tau:
          unit: "ms"
          value: 20.
      delay: *delay

    Krc_in:
       w: *weight
       # Gaussian
       A: -0.5
       a: 
           unit: "deg"
           value: 0.83
           
      # exp decay
       tau:
          unit: "ms"
          value: 20.
       delay: *delay
