name: "irf_temporal_params_mix_fb"

# Integrator settings
grid:
    nr: 7
    nt: 10
    dt:
       unit: "ms"
       value: 1
    dr:
        unit: "deg"
        value: 0.1
        
# Neuron settings
ganglion:
    # DOG
    A: 1
    a:
       unit: "deg"
       value: 0.62
    B: 0.85
    b:
       unit: "deg"
       value: 1.26

    # Biphasic
    damping: 0.38
    phase:
       unit: "ms"
       value: 43
    delay:
       unit: "ms"
       value: 0.

relay:
    Krg:
        w: 1.0
        # Gaussian
        A: 1
        a:
           unit: "deg"
           value: 0.1
           
        # exp decay
        tau:
           unit: "ms"
           value: 10.
        delay:
           unit: "ms"
           value: 0
            
    Krc_ex:
      w: 0.4
      # Gaussian
      A: 1
      a: 
          unit: "deg"
          value: 0.1
          
      # exp decay
      tau_small:
          unit: "ms"
          value: 5 
          
      tau_large:
          unit: "ms"
          value: 30 
          
      delay_small:
          unit: "ms"
          value: 0 
          
      delay_large:
          unit: "ms"
          value: 30   
   
    Krc_in:
       w: 0.4
       # Gaussian
       A: -2
       a: 
           unit: "deg"
           value: 0.9
           
       # exp decay
       tau:
           unit: "ms"
           start: 5.0
           stop: 30.
           count: 11
       delay:
           unit: "ms"
           start: 0.
           stop: 30.
           count: 11
