name: "natural_movie"

# Integrator settings
grid:
    nr: 7
    nt: 14
    dt:
       unit: "ms"
       value: 1
    dr:
        unit: "deg"
        value: 0.1

# Neuron settings
ganglion:
    # DOG
    A: 1
    a:
       unit: "deg"
       value: 0.62
    B: 0.85
    b:
       unit: "deg"
       value: 1.26

    # Biphasic
    damping: 0.38
    phase:
       unit: "ms"
       value: 43
    delay:
       unit: "ms"
       value: 0.

relay:
    Krg:
        w: 1.0
        # Gaussian
        A: 1
        a:
           unit: "deg"
           value: 0.1
           
        # exp decay
        tau:
           unit: "ms"
           value: 5.
        delay:
           unit: "ms"
           value: 0
           
    Krig:
        w: 0.5
        # Gaussian
        A: -1.0
        a:
           unit: "deg"
           value: 0.3
           
        # exp decay
        tau:
           unit: "ms"
           value: 5
        delay:
            unit: "ms"
            value: 3
          
    Krc_mix:
        w: 1
        Krc_ex:
            # Gaussian
            A: 0.3
            a: 
                unit: "deg"
                value: 0.1

        Krc_in:
            # Gaussian
            A: -0.6
            a: 
                unit: "deg"
                value: 0.9
               
         # temporal exp decay
        delayed_in:
             tau_ex:
                 unit: "ms"
                 value: 5
             tau_in:
                 unit: "ms"
                 value: 5
             delay_ex:
                 unit: "ms"
                 value: 5
             delay_in:
                 unit: "ms"
                 value: 30
                 
        synced:
             tau_ex:
                 unit: "ms"
                 value: 5
             tau_in:
                 unit: "ms"
                 value: 5
             delay_ex:
                 unit: "ms"
                 value: 15
             delay_in:
                 unit: "ms"
                 value: 15
                 
        delayed_ex:
             tau_ex:
                 unit: "ms"
                 value: 5
             tau_in:
                 unit: "ms"
                 value: 5
             delay_ex:
                 unit: "ms"
                 value: 30
             delay_in:
                 unit: "ms"
                 value: 5